### ISSUE TITLE
how to multiply two decision variables?

### ISSUE THREAD

**Issue by Stylite-Y** [XiongPengNUS/rsome#13]
hello.
I have a question about objective function, for nonlinear objective function, how to implement the multiplication of two decision variables, for example
x = model.dvar(4)
objfun = x[0] * x[1] + x[2]* x[3]
this can not implemented by operator '*', but i don not find the multiply function similar to function rso.square()

**Comment by chenzjames** [comment]
In general, multiplying two decision variables would lead to a non-convex problem. If, in some special cases, the problem remains convex, then it may be possible to try the second-order cone, which is supported in RSOME.
