### ISSUE TITLE
example reference

### ISSUE THREAD

**Issue by hzzzzjzyq** [XiongPengNUS/rsome#20]
thanks for your guide , 2019b is a error in reference 
https://xiongpengnus.github.io/rsome/example_dro_inv

**Comment by hzzzzjzyq** [comment]
model.st(I[0] == I0 + w - d[0])
NameError: name 'w' is not defined in [Multi-Stage Inventory Control](https://xiongpengnus.github.io/rsome/example_dro_inv)

**Comment by XiongPengNUS** [comment]
Thank you for spotting this typo. The variable should be x1 instead of w. We have corrected the typo in the new commit.
