### ISSUE TITLE
Debugging unsolved optimizations

### ISSUE THREAD

**Issue by anupamsobti** [XiongPengNUS/rsome#22]
Hi

Thanks for this repository! You're doing a great job. Could you help me figure out how to access functions related to unsolved constraints?

[This](https://www.gurobi.com/documentation/9.5/examples/workforce1_py.html#subsubsection:workforce1.py) Gurobi example shows an IIS that can be run to figure out conflicting constraints, although I'm not able to find this object within the rsome wrapper.

**Comment by XiongPengNUS** [comment]
Hi
Thank you for your interest in RSOME. I think checking the unsolved/conflicting constraints is at the solution stage, so RSOME as a pure modeling toolbox, does not provide such functions.

However, there might be an indirect way to check the unsolved constraints built by RSOME. Please check our website [https://xiongpengnus.github.io/rsome/get_start#section1.3](https://xiongpengnus.github.io/rsome/get_start#section1.3): we provide a `to_lp()` method, which exports an ".lp" file. You could use Gurobi to read the lp file and analyze the unsolved constraints.

**Comment by anupamsobti** [comment]
Thank you! I will try that.
