### ISSUE TITLE
error when trying to get the model status

### ISSUE THREAD

**Issue by AmalNammouchi** [XiongPengNUS/rsome#26]
Hi,
I am trying to get the model status and save it in a variable , since I am using Gurobi as a solver I tried model.status but it yields the following error: 
AttributeError: module 'rsome.ro' has no attribute 'status'

I assume there is a different way to get the status in rsome but I can't find it in the documentation.

Thank you

**Comment by XiongPengNUS** [comment]
Hi, the solution status of the solver can be accessed by the expression `model.solution.status`.
