### ISSUE TITLE
How to build two-stage robust optimization

### ISSUE THREAD

**Issue by sometimesstudy** [XiongPengNUS/rsome#45]
Hi, I am trying to build two-stage robust optimization and use it in power system robust scheduling, the formulation is as _**min cx+ maxmin ay**_, but I haven't found the  examples like this. So how can I build a model like _**min cx+ maxmin ay**_? 
Thanks a million!

**Comment by sometimesstudy** [comment]
I am wholeheartedly thankful for your reply.
So if I want to build a model with formulation of min+maxmin, I should firstly consider min cx+ ay, and next y.adapt(d)?

**Comment by chenzjames** [comment]
Yes: but putting “minimax” as the objective.

**Comment by sometimesstudy** [comment]
I have addressed my questions.
Thanks so much!
