### ISSUE TITLE
the solution may not meet the constraints.

### ISSUE THREAD

**Issue by lrw890123** [XiongPengNUS/rsome#48]
When I use the rsome.dro to solve the distributionally optimization problem, I find the solution may not meet the constraints.
I have set the constraint that decision variables are greater than 0, but negative values appeared in the solution!
![442131687230434_ pic](https://github.com/XiongPengNUS/rsome/assets/113982796/9c813e99-aa6c-4781-bfc1-356f31199c30)

**Comment by XiongPengNUS** [comment]
The `get()` function of a decision rule only returns the **constant term** of the decision rule. The negative constant term does not mean that the decision rule value can be negative. Please check the `help()` information of the `q.get` function and the [Solution Analysis](https://xiongpengnus.github.io/rsome/ro_rsome#section2.5) section.

**Comment by lrw890123** [comment]
Thanks a lot! I understand. I didn't understand and grasp LDR and this Package well before.
