### ISSUE TITLE
Will it be possible to support binary variables for rvar in the future?

### ISSUE THREAD

**Issue by sometimesstudy** [XiongPengNUS/rsome#49]
Hi Profs. @XiongPengNUS and @chenzjames,

I am wondering if it will support binary variables for _rvar_ in the future. It seems binary variables are not supported for _rvar_ in the current version. But binary variables usually appear in power system optimisation.

**Comment by XiongPengNUS** [comment]
Hi @sometimesstudy In general, the random variables cannot be defined as binary. However, for some types of uncertainty sets, the worst-case value of random variables are binaries.

**Comment by sometimesstudy** [comment]
Hi Prof. @XiongPengNUS. The operation states of transmission lines are usually regarded as binary variables in power systems, and they are random variables under uncertainties when the system suffering disasters. So is there any way to set the operation states of switches to binary random variables?

**Comment by walidzegal** [comment]
I got this exception when I try to solve the LP model in quick start : all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s). Can you help me?

**Comment by XiongPengNUS** [comment]
@sometimesstudy for power system cases, it is mentioned in [https://ietresearch.onlinelibrary.wiley.com/doi/full/10.1049/iet-gtd.2012.0660](https://ietresearch.onlinelibrary.wiley.com/doi/full/10.1049/iet-gtd.2012.0660) that the random variables representing the outage status are binaries under the worst-case scenario.

**Comment by XiongPengNUS** [comment]
@sometimesstudy for power system cases, it is mentioned in [https://ietresearch.onlinelibrary.wiley.com/doi/full/10.1049/iet-gtd.2012.0660](https://ietresearch.onlinelibrary.wiley.com/doi/full/10.1049/iet-gtd.2012.0660) that the random variables representing the outage status are binaries under the worst-case scenario.

**Comment by walidzegal** [comment]
Thank you for your response. I found my error.
Have a nice day.
