### ISSUE TITLE
Linear decision rule: adapt more historical data, but objective are not monotonically increasing/decreasing

### ISSUE THREAD

**Issue by my-hub30** [XiongPengNUS/rsome#51]
Hello friends:
     I'm using RSOME to solve an optimization model. Linear decision rule is also used. Generally, when 2nd-stage variable is adapted to more uncertainty data, the results are expected to be better. However, based on my results, the results show up and down as I increase the number of uncertainty data in adaptation. Could anyone explain about it? Or where am I wrong? Thank you!

**Comment by XiongPengNUS** [comment]
Hi @my-hub30 Can you provide the code for a small case?
