### ISSUE TITLE
automatic differentiation

### ISSUE THREAD

**Issue by babak1995** [XiongPengNUS/rsome#52]
Hi, 
I'm using rsome and wanted to integrate automatic differentiation, like with Autograd. Is rsome currently compatible with such frameworks? If not, any suggestions for a workaround?

Thanks,

**Comment by XiongPengNUS** [comment]
RSOME models constrained convex optimization problem, and the formulated problems are solved by external solvers. Since the autograd for commonly used solvers are not supported, RSOME also does not support.
