### ISSUE TITLE
Lexicon

### ISSUE THREAD

**Issue by walidzegal** [XiongPengNUS/rsome#56]
Do you have a document explaining the lexicon that you use in the modeling code?  for example, rv@rv.T, rso.tril,rso.rstack,...in test_sdp_ro.py.

**Comment by XiongPengNUS** [comment]
The `@` operator is used for matrix multiplication, and it is the same as in NumPy package. You may access the documentation of functions like `rso.tril`, `rso.rstack` using the `help` function. For example `help(rso.tril)`.
